"""Realistic VGC sets in the platform's card format, for offline testing only.

The real pool is randomized from a catalog we can't read yet; these mimic the cards seen in
the demo (same card_id style) so the draft, preview and battle logic can be exercised. Cards
seen in live matches are appended to logs/cards_seen.jsonl by the agent.
"""

def _c(species, item, ability, nature, evs, moves, card_id=None):
    cid = card_id or "vgc-" + species.lower().replace(" ", "-").replace(".", "")
    return {"card_id": cid, "species": species, "item": item, "ability": ability, "nature": nature,
            "level": 50, "evs": evs, "ivs": {}, "moves": moves}


SAMPLE_CARDS = [
    _c("Incineroar", "Sitrus Berry", "Intimidate", "Careful", {"hp": 252, "atk": 4, "def": 84, "spd": 164, "spe": 4},
       ["Fake Out", "Flare Blitz", "Knock Off", "Parting Shot"]),
    _c("Urshifu-Rapid-Strike", "Mystic Water", "Unseen Fist", "Adamant", {"hp": 4, "atk": 252, "spe": 252},
       ["Surging Strikes", "Close Combat", "Aqua Jet", "Protect"]),
    _c("Rillaboom", "Assault Vest", "Grassy Surge", "Adamant", {"hp": 252, "atk": 116, "def": 4, "spd": 76, "spe": 60},
       ["Fake Out", "Grassy Glide", "Wood Hammer", "U-turn"]),
    _c("Flutter Mane", "Booster Energy", "Protosynthesis", "Timid", {"hp": 4, "spa": 252, "spe": 252},
       ["Moonblast", "Shadow Ball", "Dazzling Gleam", "Protect"]),
    _c("Chi-Yu", "Choice Specs", "Beads of Ruin", "Modest", {"hp": 4, "spa": 252, "spe": 252},
       ["Heat Wave", "Dark Pulse", "Overheat", "Snarl"]),
    _c("Chien-Pao", "Focus Sash", "Sword of Ruin", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Icicle Crash", "Sucker Punch", "Sacred Sword", "Protect"]),
    _c("Amoonguss", "Rocky Helmet", "Regenerator", "Relaxed", {"hp": 252, "def": 172, "spd": 84},
       ["Spore", "Rage Powder", "Pollen Puff", "Protect"]),
    _c("Gholdengo", "Choice Specs", "Good as Gold", "Modest", {"hp": 252, "spa": 252, "spe": 4},
       ["Make It Rain", "Shadow Ball", "Power Gem", "Trick"]),
    _c("Landorus-Therian", "Choice Scarf", "Intimidate", "Adamant", {"hp": 4, "atk": 252, "spe": 252},
       ["Stomping Tantrum", "Rock Slide", "U-turn", "Tera Blast"]),
    _c("Tornadus", "Covert Cloak", "Prankster", "Timid", {"hp": 252, "def": 4, "spa": 4, "spd": 4, "spe": 244},
       ["Tailwind", "Bleakwind Storm", "Taunt", "Protect"]),
    _c("Iron Hands", "Booster Energy", "Quark Drive", "Adamant", {"hp": 4, "atk": 252, "spd": 252},
       ["Fake Out", "Drain Punch", "Wild Charge", "Heavy Slam"]),
    _c("Ogerpon-Hearthflame", "Hearthflame Mask", "Mold Breaker", "Adamant", {"hp": 4, "atk": 252, "spe": 252},
       ["Ivy Cudgel", "Horn Leech", "Follow Me", "Spiky Shield"]),
    _c("Kingambit", "Black Glasses", "Defiant", "Adamant", {"hp": 252, "atk": 252, "spd": 4},
       ["Kowtow Cleave", "Sucker Punch", "Iron Head", "Protect"]),
    _c("Dragonite", "Choice Band", "Multiscale", "Adamant", {"hp": 252, "atk": 252, "spe": 4},
       ["Extreme Speed", "Stomping Tantrum", "Ice Spinner", "Iron Head"]),
    _c("Indeedee-F", "Psychic Seed", "Psychic Surge", "Bold", {"hp": 252, "def": 252, "spd": 4},
       ["Follow Me", "Helping Hand", "Trick Room", "Protect"]),
    _c("Farigiraf", "Electric Seed", "Armor Tail", "Quiet", {"hp": 252, "def": 116, "spa": 140},
       ["Trick Room", "Psychic Noise", "Hyper Voice", "Helping Hand"]),
    _c("Ursaluna-Bloodmoon", "Life Orb", "Mind's Eye", "Modest", {"hp": 252, "spa": 252, "spd": 4},
       ["Blood Moon", "Earth Power", "Hyper Voice", "Protect"]),
    _c("Whimsicott", "Focus Sash", "Prankster", "Timid", {"hp": 4, "spa": 252, "spe": 252},
       ["Tailwind", "Moonblast", "Encore", "Protect"]),
    _c("Grimmsnarl", "Light Clay", "Prankster", "Careful", {"hp": 252, "atk": 4, "spd": 252},
       ["Reflect", "Light Screen", "Spirit Break", "Thunder Wave"]),
    _c("Gyarados", "Wacan Berry", "Intimidate", "Adamant", {"hp": 252, "atk": 116, "spe": 140},
       ["Waterfall", "Dragon Dance", "Thunder Wave", "Protect"]),
    _c("Garchomp", "Clear Amulet", "Rough Skin", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Earthquake", "Dragon Claw", "Rock Slide", "Protect"]),
    _c("Dondozo", "Leftovers", "Unaware", "Impish", {"hp": 252, "def": 252, "spd": 4},
       ["Wave Crash", "Order Up", "Yawn", "Protect"]),
    _c("Archaludon", "Power Herb", "Stamina", "Modest", {"hp": 244, "spa": 252, "spe": 12},
       ["Electro Shot", "Flash Cannon", "Draco Meteor", "Protect"]),
    _c("Basculegion", "Choice Scarf", "Adaptability", "Adamant", {"hp": 4, "atk": 252, "spe": 252},
       ["Wave Crash", "Last Respects", "Aqua Jet", "Flip Turn"]),
    _c("Wo-Chien", "Leftovers", "Tablets of Ruin", "Careful", {"hp": 252, "def": 4, "spd": 252},
       ["Leech Seed", "Pollen Puff", "Foul Play", "Protect"]),
    _c("Iron Bundle", "Booster Energy", "Quark Drive", "Timid", {"hp": 4, "spa": 252, "spe": 252},
       ["Freeze-Dry", "Icy Wind", "Hydro Pump", "Protect"]),
    _c("Thundurus", "Sitrus Berry", "Prankster", "Timid", {"hp": 252, "spa": 4, "spe": 252},
       ["Thunderbolt", "Thunder Wave", "Taunt", "Protect"]),
    _c("Hatterene", "Life Orb", "Magic Bounce", "Quiet", {"hp": 252, "spa": 252, "spd": 4},
       ["Expanding Force", "Dazzling Gleam", "Trick Room", "Protect"]),
    _c("Cresselia", "Mental Herb", "Levitate", "Relaxed", {"hp": 252, "def": 252, "spd": 4},
       ["Trick Room", "Lunar Blessing", "Moonblast", "Helping Hand"]),
    _c("Porygon2", "Eviolite", "Download", "Sassy", {"hp": 252, "def": 124, "spd": 132},
       ["Trick Room", "Tri Attack", "Recover", "Ice Beam"]),
    _c("Torkoal", "Charcoal", "Drought", "Quiet", {"hp": 252, "spa": 252, "spd": 4},
       ["Eruption", "Heat Wave", "Earth Power", "Protect"]),
    _c("Lilligant-Hisui", "Choice Scarf", "Chlorophyll", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Close Combat", "Leaf Blade", "Ice Spinner", "Sleep Powder"]),
    _c("Pelipper", "Damp Rock", "Drizzle", "Bold", {"hp": 252, "def": 252, "spa": 4},
       ["Weather Ball", "Hurricane", "Tailwind", "Wide Guard"]),
    _c("Raging Bolt", "Booster Energy", "Protosynthesis", "Modest", {"hp": 244, "spa": 252, "spe": 12},
       ["Thunderclap", "Draco Meteor", "Thunderbolt", "Protect"]),
    _c("Sneasler", "White Herb", "Unburden", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Fake Out", "Close Combat", "Dire Claw", "Protect"]),
    _c("Annihilape", "Choice Scarf", "Defiant", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Rage Fist", "Drain Punch", "Final Gambit", "Coaching"]),
    _c("Maushold", "Wide Lens", "Technician", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Population Bomb", "Follow Me", "Taunt", "Protect"]),
    _c("Volcarona", "Leftovers", "Flame Body", "Modest", {"hp": 252, "def": 4, "spa": 252},
       ["Heat Wave", "Giga Drain", "Quiver Dance", "Protect"]),
    _c("Iron Boulder", "Shuca Berry", "Quark Drive", "Jolly", {"hp": 4, "atk": 252, "spe": 252},
       ["Mighty Cleave", "Close Combat", "Zen Headbutt", "Protect"]),
    _c("Glimmora", "Expert Belt", "Toxic Debris", "Modest", {"hp": 4, "spa": 252, "spe": 252},
       ["Sludge Bomb", "Power Gem", "Earth Power", "Mortal Spin"]),
]
